#-------------------------------
# General Site Settings
title: HomePage
logo: <span style="font-weight:normal">Damien</span> GRASSET
description: Personal homepage for scientific posts and profil 

#-------------------------------
# Author Settings
author:
  name: Damien GRASSET
  image: 01.jpg
  #say-hello: Hello, I’m <strong>Damien GRASSET</strong>
  bio: Graduated as a statician-economist engineer from ENSAE, I'm currently working as a research engineer at IRT Saint Exupery Canada, investigating <strong>explanability</strong> and <strong>causality</strong> in <strong>reinforcement learning</strong>.
  job-company: IRT Saint-Exupéry Canada
  job-adress: 6650 Rue Saint-Urbain (MILA), Montréal, QC H2S 3H1, Canada

#-------------------------------
# Contact links
github: https://github.com/ # Add your Github handle
school: https://scholar.google.com/ # Add your Scholar handle
linkedin: https://linkedin.com/in/ # Add your Linkedin handle
email: True

#-------------------------------
# Comment Section (Disqus)
disqus-identifier: dam-grassman # add your shortname for Disqus Comment. For example mr-brown

#-------------------------------
# Linkedin Feed
linkedin-profile: damien-grasset-2a6971115 # Add instagram username

#-------------------------------
# Github Feed
github-profile: dam-grassman # Add instagram username

#-------------------------------
# Scholar Feed
school-profile: citations?hl=fr&user=Ft5CXT4AAAAJ # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.

#-------------------------------
# Email adress
email-adress: damien-grasset@hotmail.fr

#instafeed: True